"""
Sanity Checker
==============
Validates every normalized listing before it enters the active database.

A listing is REJECTED (moved to property_anomalies) if it fails any of:
  1. SOURCE_REQUIRED  — no real source URL or listing ID (catches mock/synthetic data)
  2. MOCK_DATA        — source == "mock" (explicitly blocked from active pipeline)
  3. PRICE_IMPLAUSIBLE — price is below the city floor for a typical residential listing
  4. PRICE_PER_SQFT   — price/sqft is outside a plausible Bay Area range
  5. ADDRESS_GENERIC  — address looks synthetic (no street number, or known fake patterns)

Floors are conservative — they intentionally allow distressed/land/TIC deals through.
If a deal is legitimately cheap (fire sale, land only), the agent remarks will explain it.

Add new cities or adjust floors in CITY_PRICE_FLOORS below.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)

# ── City price floors (minimum plausible list price for a residential listing) ─
# Source: Redfin median sale data, Feb 2026, with 40–50% haircut to allow
# distressed / land / TIC / auction deals through.
# Raise these if the market moves up significantly.

CITY_PRICE_FLOORS: dict[str, float] = {
    # Contra Costa
    "richmond":       250_000,
    "san pablo":      200_000,
    "el cerrito":     500_000,
    "pinole":         350_000,
    "hercules":       450_000,
    "martinez":       350_000,
    "concord":        350_000,
    "walnut creek":   600_000,
    # Alameda
    "oakland":        300_000,
    "berkeley":       650_000,
    "albany":         750_000,
    "emeryville":     450_000,
    "hayward":        450_000,
    "san leandro":    450_000,
    "fremont":        700_000,
    "newark":         600_000,
    "union city":     550_000,
    # Solano (bonus targets)
    "vallejo":        200_000,
    "benicia":        400_000,
    "fairfield":      300_000,
}

# Price per sqft sanity range for Bay Area residential
PRICE_PER_SQFT_MIN = 100.0   # below this = implausible (teardown land-only maybe)
PRICE_PER_SQFT_MAX = 2_500.0 # above this = likely data error

# Street patterns that look synthetic (generated by mock adapter)
_FAKE_STREET_PATTERNS = [
    r"^\d+\s+(Market|Central|Elm|Hilltop|Broadway|Church|College|Main)\s+(Dr|Ln|Ct|Way|Pl)$",
]


@dataclass
class SanityResult:
    passed: bool
    rejection_code: Optional[str]
    rejection_reason: Optional[str]


def check(normalized: dict) -> SanityResult:
    """
    Run all sanity checks on a normalized listing dict.
    Returns SanityResult with passed=True if the listing is acceptable.
    """

    source = (normalized.get("source") or "").lower()
    source_url = (normalized.get("listing_url") or "").strip()
    source_id = (normalized.get("external_id") or "").strip()
    city_raw = (normalized.get("city") or "").lower().strip()
    price = normalized.get("list_price")
    sqft = normalized.get("sqft")
    address = (normalized.get("address") or "").strip()

    # ── 1. Block mock data entirely from active pipeline ──────────────────────
    if source == "mock":
        return SanityResult(
            passed=False,
            rejection_code="MOCK_DATA",
            rejection_reason=(
                "Listing is from the mock/synthetic adapter. "
                "Run with --source redfin to ingest real listings. "
                "Mock data is for pipeline testing only."
            ),
        )

    # ── 2. Require a real source URL ──────────────────────────────────────────
    if not source_url or not source_url.startswith("http"):
        return SanityResult(
            passed=False,
            rejection_code="NO_SOURCE_URL",
            rejection_reason=(
                f"No valid source URL (got: '{source_url}'). "
                "Cannot verify this is a real listing. Rejected until source URL is confirmed."
            ),
        )

    # ── 3. Require a listing ID (relaxed for Craigslist — CL-* IDs are OK) ──
    if not source_id and source != "craigslist":
        return SanityResult(
            passed=False,
            rejection_code="NO_LISTING_ID",
            rejection_reason=(
                "No source listing ID (MLS# or equivalent). "
                "Cannot deduplicate or verify this listing."
            ),
        )

    # ── 4. City price floor ───────────────────────────────────────────────────
    if price and city_raw:
        floor = CITY_PRICE_FLOORS.get(city_raw)
        if floor and price < floor:
            return SanityResult(
                passed=False,
                rejection_code="PRICE_IMPLAUSIBLE",
                rejection_reason=(
                    f"${price:,.0f} is below the sanity floor of ${floor:,.0f} for {city_raw.title()}. "
                    f"Feb 2026 medians: Albany ~$1.56M, Berkeley ~$1.29M, Fremont ~$1.46M, "
                    f"Oakland ~$740k, Richmond ~$500k. "
                    f"This price is likely a parser error, synthetic data, or a non-residential listing. "
                    f"If legitimately cheap (fire damage, land-only, TIC), add a manual override."
                ),
            )

    # ── 5. Price per sqft sanity ──────────────────────────────────────────────
    if price and sqft and sqft > 0:
        ppsf = price / sqft
        if ppsf < PRICE_PER_SQFT_MIN:
            return SanityResult(
                passed=False,
                rejection_code="PPSF_TOO_LOW",
                rejection_reason=(
                    f"${ppsf:.0f}/sqft is implausibly low for Bay Area residential. "
                    f"Min expected: ${PRICE_PER_SQFT_MIN:.0f}/sqft. "
                    "Likely a data parsing error (e.g., sqft field contains lot size instead of living area)."
                ),
            )
        if ppsf > PRICE_PER_SQFT_MAX:
            return SanityResult(
                passed=False,
                rejection_code="PPSF_TOO_HIGH",
                rejection_reason=(
                    f"${ppsf:.0f}/sqft is implausibly high. "
                    f"Max expected: ${PRICE_PER_SQFT_MAX:.0f}/sqft. Likely a data error."
                ),
            )

    # ── 6. Generic/synthetic address pattern (skip for Craigslist — addresses are approximate) ──
    if source != "craigslist":
        for pattern in _FAKE_STREET_PATTERNS:
            if re.match(pattern, address, re.IGNORECASE):
                return SanityResult(
                    passed=False,
                    rejection_code="ADDRESS_GENERIC",
                    rejection_reason=(
                        f"Address '{address}' matches a known synthetic/generic pattern. "
                        "This looks like mock data that slipped through the source filter."
                    ),
                )

    # ── All checks passed ─────────────────────────────────────────────────────
    return SanityResult(passed=True, rejection_code=None, rejection_reason=None)


def log_anomaly(db, normalized: dict, result: SanityResult) -> None:
    """Persist a rejected listing to the property_anomalies table."""
    from database.models import PropertyAnomaly

    anomaly = PropertyAnomaly(
        raw_address=normalized.get("address"),
        raw_city=normalized.get("city"),
        raw_zip=normalized.get("zip_code"),
        raw_price=normalized.get("list_price"),
        raw_beds=normalized.get("beds"),
        raw_sqft=normalized.get("sqft"),
        source=normalized.get("source"),
        source_listing_id=normalized.get("external_id"),
        source_url=normalized.get("listing_url"),
        rejection_reason=result.rejection_reason or "",
        rejection_code=result.rejection_code or "UNKNOWN",
    )
    db.add(anomaly)
    logger.debug(
        "Anomaly logged [%s]: %s, %s — %s",
        result.rejection_code,
        normalized.get("address"),
        normalized.get("city"),
        result.rejection_reason[:80] if result.rejection_reason else "",
    )
