"""initial schema with indexes

Revision ID: 4957778c1d51
Revises: 
Create Date: 2026-04-03 15:51:10.856436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4957778c1d51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_prop_type_sent', ['property_id', 'alert_type', 'sent'], unique=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('listing_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'sale'::character varying"))
        batch_op.create_index('ix_prop_address_zip', ['address', 'zip_code'], unique=False)
        batch_op.create_index('ix_prop_city', ['city'], unique=False)
        batch_op.create_index('ix_prop_external_source', ['external_id', 'source'], unique=False)
        batch_op.create_index('ix_prop_score', ['total_score'], unique=False)
        batch_op.create_index('ix_prop_status_archived_type', ['status', 'is_archived', 'listing_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index('ix_prop_status_archived_type')
        batch_op.drop_index('ix_prop_score')
        batch_op.drop_index('ix_prop_external_source')
        batch_op.drop_index('ix_prop_city')
        batch_op.drop_index('ix_prop_address_zip')
        batch_op.alter_column('listing_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'sale'::character varying"))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_prop_type_sent')

    # ### end Alembic commands ###
